// CSV export for the nine data-heavy reports.
//
// ─── WHY THIS CANNOT DRIFT FROM THE PDF ──────────────────────────────────
// Nothing here computes anything. Every function below takes the SAME result
// object the PDF template renders — the one produced by the report's single
// pure compute function in this directory — and flattens it into rows. The API
// route calls compute() once and hands the identical object to either the PDF
// renderer or this module, so a CSV and a PDF of the same report over the same
// range are two renderings of one calculation, not two calculations.
// ─────────────────────────────────────────────────────────────────────────
//
// Board Summary is deliberately absent: it is a one-page narrative of headline
// figures, and its detail already lives in the nine reports it summarises.
//
// Pure. No DB access, no dependency — a CSV writer is a dozen lines.

import type { HeadcountResult } from "./headcount.ts";
import type { AttendanceResult } from "./attendance.ts";
import type { HiresExitsResult } from "./hires-exits.ts";
import type { ProductionResult } from "./production.ts";
import type { AppraisalDistributionResult } from "./appraisal-distribution.ts";
import type { PayrollCostResult } from "./payroll-cost.ts";
import { COST_COMPONENTS, COMPONENT_LABEL } from "./payroll-cost.ts";
import type { RecruitmentFunnelResult } from "./recruitment-funnel.ts";
import type { IdleTimeResult } from "./idle-time.ts";
import type { WarningLettersResult } from "./warning-letters.ts";
import { ymd } from "./range.ts";
import { scoreOutOfFive, formatBandLabelOutOfFive } from "../appraisal/display.ts";

export type CsvCell = string | number | null | undefined;

export interface CsvSection {
  /** Printed as a title row above the section's header row. */
  title: string;
  headers: string[];
  rows: CsvCell[][];
}

/**
 * RFC-4180 escaping: a field is quoted when it contains a comma, a quote, or a
 * newline, and embedded quotes are doubled. null/undefined become an empty
 * field — never the string "null" — so a spreadsheet shows a blank, matching
 * the "—" the PDF prints for missing data.
 */
export function escapeCsvCell(value: CsvCell): string {
  if (value === null || value === undefined) return "";
  const s = String(value);
  if (/[",\r\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

function sectionToLines(section: CsvSection): string[] {
  const lines = [escapeCsvCell(section.title)];
  lines.push(section.headers.map(escapeCsvCell).join(","));
  for (const row of section.rows) lines.push(row.map(escapeCsvCell).join(","));
  return lines;
}

/**
 * Serialize one or more sections into a single CSV document.
 *
 * Multi-section rather than one flat table because these reports genuinely have
 * several shapes (summary, by-department, by-employee). Sections are separated
 * by a blank line and introduced by a title row, which every spreadsheet opens
 * correctly and a human can read top to bottom.
 *
 * CRLF line endings per RFC 4180 — Excel on Windows is the overwhelmingly
 * likely destination for these files.
 */
export function serializeCsv(sections: CsvSection[], meta?: CsvMeta): string {
  const blocks: string[][] = [];
  if (meta) {
    blocks.push([
      escapeCsvCell(meta.title),
      ["Period", meta.startLabel, "to", meta.endLabel].map(escapeCsvCell).join(","),
      ["Scope", meta.scopeLabel].map(escapeCsvCell).join(","),
      ["Generated by", meta.generatedBy].map(escapeCsvCell).join(","),
      ["Generated at", meta.generatedAt.toISOString()].map(escapeCsvCell).join(","),
    ]);
  }
  for (const s of sections) blocks.push(sectionToLines(s));
  return blocks.map((b) => b.join("\r\n")).join("\r\n\r\n") + "\r\n";
}

export interface CsvMeta {
  title: string;
  startLabel: string;
  endLabel: string;
  scopeLabel: string;
  generatedBy: string;
  generatedAt: Date;
}

// ── One section-builder per report. Reads results, computes nothing. ───────

export function headcountCsv(r: HeadcountResult): CsvSection[] {
  return [
    {
      title: "Summary",
      headers: ["Measure", "Value"],
      rows: [
        ["Active headcount", r.totalActive],
        ["Departments", r.departmentCount],
        ["Headcount at period start", r.atRangeStart],
        ["Headcount at period end", r.atRangeEnd],
        ["Net change", r.netChange],
      ],
    },
    {
      title: "Headcount by department",
      headers: ["Department", "Employees"],
      rows: r.byDepartment.map((d) => [d.department, d.count]),
    },
  ];
}

export function attendanceCsv(r: AttendanceResult): CsvSection[] {
  return [
    {
      title: "Summary",
      headers: ["Measure", "Value"],
      rows: [
        ["Days punched", r.totalPunchDays],
        ["On time", r.onTimeCount],
        ["Late", r.lateCount],
        ["Late %", r.latePct],
        ["Average punch-in (org)", r.orgAvgPunchIn],
        ["Average punch-in minutes since midnight", r.orgAvgPunchInMinutes],
        ["Average punch-in method", r.orgAvgPunchInMethod],
        ["Expected employee-weekdays", r.expectedWeekdayCount],
        ["Days with no punch", r.noPunchDays],
      ],
    },
    {
      title: "By department",
      headers: [
        "Department", "Employees", "Days punched", "Late", "Late %",
        "Avg punch-in", "Mean type",
      ],
      rows: r.byDepartment.map((d) => [
        d.department, d.employees, d.punchDays, d.lateCount, d.latePct,
        d.avgPunchIn, d.avgPunchInMethod,
      ]),
    },
    {
      title: "By employee",
      headers: [
        "Employee code", "Name", "Department", "Days punched", "Late", "On time",
        "Late %", "Avg late minutes", "Avg punch-in", "Mean type",
      ],
      rows: r.byEmployee.map((e) => [
        e.employeeCode, e.name, e.department, e.punchDays, e.lateCount, e.onTimeCount,
        e.latePct, e.avgLateMinutes, e.avgPunchIn, e.avgPunchInMethod,
      ]),
    },
  ];
}

export function hiresExitsCsv(r: HiresExitsResult): CsvSection[] {
  return [
    {
      title: "Summary",
      headers: ["Measure", "Value"],
      rows: [
        ["New hires", r.hireCount],
        ["Exits", r.exitCount],
        ["Net change", r.netChange],
        ["Average headcount", r.avgHeadcount],
        ["Attrition %", r.attritionPct],
      ],
    },
    {
      title: "By department",
      headers: ["Department", "Hires", "Exits", "Net"],
      rows: r.byDepartment.map((d) => [d.department, d.hires, d.exits, d.net]),
    },
    {
      title: "New hires",
      headers: ["Joining date", "Employee code", "Name", "Department"],
      rows: r.hires.map((h) => [ymd(h.date), h.employeeCode, h.name, h.department]),
    },
    {
      title: "Exits",
      headers: ["Last working day", "Employee code", "Name", "Department"],
      rows: r.exits.map((x) => [ymd(x.date), x.employeeCode, x.name, x.department]),
    },
    {
      title: "Monthly movement",
      headers: ["Month", "Hires", "Exits"],
      rows: r.byMonth.map((m) => [m.month, m.hires, m.exits]),
    },
  ];
}

export function productionCsv(r: ProductionResult): CsvSection[] {
  return [
    {
      title: "Summary",
      headers: ["Measure", "Value"],
      rows: [
        ["Units produced", r.totalActual],
        ["Target", r.totalTarget],
        ["Achievement %", r.achievementPct],
        ["Variance", r.variance],
        ["Met target", r.metTargetCount],
        ["Below target", r.belowTargetCount],
      ],
    },
    {
      title: "By department",
      headers: ["Department", "Employees", "Actual", "Target", "Achievement %", "Variance"],
      rows: r.byDepartment.map((d) => [
        d.department, d.employees, d.actual, d.target, d.achievementPct, d.variance,
      ]),
    },
    {
      title: "By employee",
      headers: [
        "Employee code", "Name", "Department", "Days", "Actual", "Target",
        "Achievement %", "Variance",
      ],
      rows: r.byEmployee.map((e) => [
        e.employeeCode, e.name, e.department, e.days, e.actual, e.target,
        e.achievementPct, e.variance,
      ]),
    },
  ];
}

export function appraisalDistributionCsv(r: AppraisalDistributionResult): CsvSection[] {
  return [
    {
      title: "Summary",
      headers: ["Measure", "Value"],
      rows: [
        ["Scores published", r.scoredCount],
        // Both scales are emitted: the /5 figure matches what people see in
        // the app, and the raw 0-100 value is what the engine actually stores
        // — a spreadsheet is exactly where someone needs to recompute against
        // the real numbers.
        ["Average (of 5)", scoreOutOfFive(r.average)],
        ["Average (raw 0-100)", r.average],
        ["Median (of 5)", scoreOutOfFive(r.median)],
        ["Median (raw 0-100)", r.median],
        ["Lowest (of 5)", scoreOutOfFive(r.min)],
        ["Highest (of 5)", scoreOutOfFive(r.max)],
      ],
    },
    {
      title: "Score distribution",
      headers: ["Band (of 5)", "Band (raw 0-100)", "Employees", "Share %"],
      rows: r.bands.map((b) => [
        formatBandLabelOutOfFive(b.min, b.max),
        b.label,
        b.count,
        b.sharePct,
      ]),
    },
    {
      title: "Average by department",
      headers: ["Department", "Scored", "Average (of 5)", "Average (raw 0-100)"],
      rows: r.byDepartment.map((d) => [
        d.department,
        d.count,
        scoreOutOfFive(d.average),
        d.average,
      ]),
    },
    {
      title: "By cycle",
      headers: ["Cycle", "Scored", "Average (of 5)", "Average (raw 0-100)"],
      rows: r.byCycle.map((c) => [
        c.cyclePeriod,
        c.count,
        scoreOutOfFive(c.average),
        c.average,
      ]),
    },
  ];
}

export function payrollCostCsv(r: PayrollCostResult): CsvSection[] {
  return [
    {
      title: "Summary (FINALIZED payroll only)",
      headers: ["Measure", "Value"],
      rows: [
        ["Payslips counted", r.finalizedRowCount],
        ["Rows excluded (not finalized)", r.excludedRowCount],
        ["Distinct employees", r.distinctEmployees],
        ["Total gross", r.totalGross],
        ["Total deductions", r.totalDeductions],
        ["Total net", r.totalNet],
        ["Total cost to company", r.totalCostToCompany],
      ],
    },
    {
      title: "Cost by component",
      headers: ["Component", "Amount"],
      rows: COST_COMPONENTS.map((k) => [COMPONENT_LABEL[k], r.components[k]]),
    },
    {
      title: "By month",
      headers: ["Month", "Payslips", "Gross", "Net", "Cost to company"],
      rows: r.byMonth.map((m) => [m.month, m.rows, m.gross, m.net, m.costToCompany]),
    },
    {
      title: "By department",
      headers: ["Department", "Employees", "Gross", "Net", "Cost to company"],
      rows: r.byDepartment.map((d) => [
        d.department, d.employees, d.gross, d.net, d.costToCompany,
      ]),
    },
  ];
}

export function recruitmentFunnelCsv(r: RecruitmentFunnelResult): CsvSection[] {
  return [
    {
      title: "Summary",
      headers: ["Measure", "Value"],
      rows: [
        ["Applications", r.totalApplications],
        ["Hired", r.hiredCount],
        ["Rejected", r.rejectedCount],
        ["Overall conversion %", r.overallConversionPct],
        ["Average time to hire (days)", r.avgTimeToHireDays],
        ["Median time to hire (days)", r.medianTimeToHireDays],
      ],
    },
    {
      title: "Pipeline funnel",
      headers: ["Stage", "Reached", "Currently at", "Conversion from previous %", "Of all %"],
      rows: r.stages.map((s) => [
        s.stage, s.reached, s.atStage, s.conversionFromPrevPct, s.ofTotalPct,
      ]),
    },
    {
      title: "By department",
      headers: ["Department", "Applications", "Hired", "Rejected", "Conversion %"],
      rows: r.byDepartment.map((d) => [
        d.department, d.applications, d.hired, d.rejected, d.conversionPct,
      ]),
    },
  ];
}

export function idleTimeCsv(r: IdleTimeResult): CsvSection[] {
  return [
    {
      title: "Summary",
      headers: ["Measure", "Value"],
      rows: [
        ["Active minutes", r.totalActiveMinutes],
        ["Idle minutes", r.totalIdleMinutes],
        ["Total tracked minutes", r.totalMinutes],
        ["Active %", r.activePct],
        ["Employees with data", r.employeesWithData],
        ["Employees in scope", r.employeesInScope],
      ],
    },
    {
      title: "By department",
      headers: ["Department", "Employees tracked", "Active minutes", "Idle minutes", "Active %"],
      rows: r.byDepartment.map((d) => [
        d.department, d.employeesTracked, d.activeMinutes, d.idleMinutes, d.activePct,
      ]),
    },
    {
      title: "By employee",
      headers: [
        "Employee code", "Name", "Department", "Days with data",
        "Active minutes", "Idle minutes", "Active %",
      ],
      rows: r.byEmployee
        .filter((e) => e.totalMinutes > 0)
        .map((e) => [
          e.employeeCode, e.name, e.department, e.daysWithData,
          e.activeMinutes, e.idleMinutes, e.activePct,
        ]),
    },
  ];
}

export function warningLettersCsv(r: WarningLettersResult): CsvSection[] {
  return [
    {
      title: "Summary (RELEASED letters only)",
      headers: ["Measure", "Value"],
      rows: [
        ["Letters released", r.releasedCount],
        ["Drafts excluded", r.excludedDraftCount],
        ["Employees affected", r.employeesAffected],
        ["Repeat cases", r.repeatEmployees.length],
      ],
    },
    {
      title: "By department",
      headers: ["Department", "Released", "Share %"],
      rows: r.byDepartment.map((d) => [d.department, d.count, d.sharePct]),
    },
    {
      title: "Monthly trend",
      headers: ["Month", "Released"],
      rows: r.byMonth.map((m) => [m.month, m.count]),
    },
    {
      title: "Employees with more than one letter",
      headers: ["Employee code", "Name", "Department", "Letters"],
      rows: r.repeatEmployees.map((e) => [e.employeeCode, e.name, e.department, e.count]),
    },
  ];
}
