/**
 * The shared report PDF layout — three primitives, composed by all ten report
 * templates in lib/reports/pdf/.
 *
 *   <ReportDocument>  page frame, branded header (title, range, generated-by /
 *                     generated-at) and the fixed footer
 *   <SummaryStats>    the strip of headline numbers at the top of a report
 *   <DataTable>       columns + rows, one consistent table style
 *
 * No report template writes its own header, footer or table styling. Styling
 * intentionally mirrors lib/payroll/pdf.tsx (same Helvetica, same rule under
 * the company name, same muted footer) so a report and a payslip read as
 * documents from one system.
 */
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";

// ponytail: same single-tenant constant as lib/payroll/pdf.tsx. Both move to
// an Organisation row together if SESS ever serves more than one company.
const COMPANY_NAME = "Simplen";

const s = StyleSheet.create({
  page: { padding: 32, fontSize: 8.5, color: "#1a1a1a", fontFamily: "Helvetica" },

  company: { fontSize: 15, fontFamily: "Helvetica-Bold", color: "#111" },
  docTitle: { fontSize: 10, marginTop: 3, color: "#555", letterSpacing: 1 },
  rule: { borderBottomWidth: 1.5, borderBottomColor: "#111", marginTop: 8, marginBottom: 12 },

  metaRow: { flexDirection: "row", flexWrap: "wrap", marginBottom: 14 },
  metaCell: { flexDirection: "row", marginRight: 20, marginBottom: 3 },
  metaLabel: { color: "#666", marginRight: 5 },
  metaValue: { fontFamily: "Helvetica-Bold" },

  statsRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 14 },
  statBox: {
    borderWidth: 1,
    borderColor: "#ddd",
    paddingVertical: 6,
    paddingHorizontal: 9,
    minWidth: 96,
  },
  statLabel: { fontSize: 6.5, color: "#666", letterSpacing: 0.4, textTransform: "uppercase" },
  statValue: { fontSize: 13, fontFamily: "Helvetica-Bold", marginTop: 3 },
  statHint: { fontSize: 6.5, color: "#888", marginTop: 2 },

  sectionTitle: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    backgroundColor: "#f2f2f2",
    borderWidth: 1,
    borderColor: "#ddd",
    paddingVertical: 5,
    paddingHorizontal: 8,
    marginTop: 12,
  },
  tableBox: { borderWidth: 1, borderTopWidth: 0, borderColor: "#ddd", marginBottom: 4 },
  tHead: {
    flexDirection: "row",
    backgroundColor: "#fafafa",
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
    paddingVertical: 5,
    fontFamily: "Helvetica-Bold",
  },
  tRow: {
    flexDirection: "row",
    paddingVertical: 4,
    borderBottomWidth: 0.5,
    borderBottomColor: "#eee",
  },
  tRowAlt: { backgroundColor: "#fcfcfc" },
  cell: { paddingHorizontal: 7 },
  emptyRow: { paddingVertical: 10, paddingHorizontal: 8, color: "#888" },

  note: { marginTop: 8, fontSize: 7, color: "#777", lineHeight: 1.5 },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 32,
    right: 32,
    fontSize: 7,
    color: "#888",
    textAlign: "center",
    borderTopWidth: 1,
    borderTopColor: "#eee",
    paddingTop: 5,
  },
});

// ── Primitive 1: the document frame + header ───────────────────────────────

export interface ReportMeta {
  /** e.g. "Attendance & Punctuality". */
  title: string;
  startLabel: string; // "YYYY-MM-DD"
  endLabel: string;
  generatedBy: string;
  generatedAt: Date;
  /** "Organisation-wide", "Your team (8 employees)", "Assembly department". */
  scopeLabel: string;
}

function iso(d: Date): string {
  return d.toISOString().slice(0, 16).replace("T", " ");
}

export function ReportDocument({
  meta,
  children,
}: {
  meta: ReportMeta;
  children: React.ReactNode;
}) {
  return (
    <Document
      title={`${meta.title} ${meta.startLabel} to ${meta.endLabel}`}
      author={COMPANY_NAME}
      subject={`${meta.title} — ${meta.scopeLabel}`}
    >
      <Page size="A4" orientation="portrait" style={s.page}>
        <Text style={s.company}>{COMPANY_NAME}</Text>
        <Text style={s.docTitle}>{meta.title.toUpperCase()}</Text>
        <View style={s.rule} />

        <View style={s.metaRow}>
          <View style={s.metaCell}>
            <Text style={s.metaLabel}>Period</Text>
            <Text style={s.metaValue}>
              {meta.startLabel} to {meta.endLabel}
            </Text>
          </View>
          <View style={s.metaCell}>
            <Text style={s.metaLabel}>Scope</Text>
            <Text style={s.metaValue}>{meta.scopeLabel}</Text>
          </View>
          <View style={s.metaCell}>
            <Text style={s.metaLabel}>Generated by</Text>
            <Text style={s.metaValue}>{meta.generatedBy}</Text>
          </View>
          <View style={s.metaCell}>
            <Text style={s.metaLabel}>Generated at</Text>
            <Text style={s.metaValue}>{iso(meta.generatedAt)} UTC</Text>
          </View>
        </View>

        {children}

        <Text style={s.footer} fixed>
          Computer-generated report · {COMPANY_NAME} · figures cover{" "}
          {meta.startLabel} to {meta.endLabel} only
        </Text>
      </Page>
    </Document>
  );
}

// ── Primitive 2: the summary-stats strip ───────────────────────────────────

export interface SummaryStat {
  label: string;
  value: string | number;
  hint?: string;
}

export function SummaryStats({ stats }: { stats: SummaryStat[] }) {
  if (stats.length === 0) return null;
  return (
    <View style={s.statsRow}>
      {stats.map((st) => (
        <View style={s.statBox} key={st.label}>
          <Text style={s.statLabel}>{st.label}</Text>
          <Text style={s.statValue}>{String(st.value)}</Text>
          {st.hint ? <Text style={s.statHint}>{st.hint}</Text> : null}
        </View>
      ))}
    </View>
  );
}

// ── Primitive 3: the data table ────────────────────────────────────────────

export interface TableColumn<T> {
  /** Header text. */
  label: string;
  /** Percentage width, e.g. "25%". Should sum to 100 across the columns. */
  width: string;
  align?: "left" | "right";
  /** Cell text. Returning "—" for missing data is the convention everywhere. */
  value: (row: T) => string;
}

export function DataTable<T>({
  title,
  columns,
  rows,
  emptyMessage = "No data in this period.",
  maxRows,
}: {
  title?: string;
  columns: TableColumn<T>[];
  rows: T[];
  emptyMessage?: string;
  /** Cap long tables; the count of omitted rows is printed underneath. */
  maxRows?: number;
}) {
  const shown = maxRows ? rows.slice(0, maxRows) : rows;
  const omitted = rows.length - shown.length;

  return (
    <View wrap>
      {title ? <Text style={s.sectionTitle}>{title.toUpperCase()}</Text> : null}
      <View style={s.tableBox}>
        <View style={s.tHead} fixed>
          {columns.map((c) => (
            <Text
              key={c.label}
              style={[s.cell, { width: c.width, textAlign: c.align ?? "left" }]}
            >
              {c.label}
            </Text>
          ))}
        </View>
        {shown.map((row, i) => (
          <View style={i % 2 === 1 ? [s.tRow, s.tRowAlt] : s.tRow} key={i} wrap={false}>
            {columns.map((c) => (
              <Text
                key={c.label}
                style={[s.cell, { width: c.width, textAlign: c.align ?? "left" }]}
              >
                {c.value(row)}
              </Text>
            ))}
          </View>
        ))}
        {shown.length === 0 && <Text style={s.emptyRow}>{emptyMessage}</Text>}
      </View>
      {omitted > 0 && (
        <Text style={s.note}>
          Showing the first {shown.length} of {rows.length} rows; {omitted} omitted
          for length.
        </Text>
      )}
    </View>
  );
}

/** Explanatory footnote under a table — used for the honest-caveat text. */
export function Note({ children }: { children: React.ReactNode }) {
  return <Text style={s.note}>{children}</Text>;
}

/** Every template ends here. One place that knows how to produce the buffer. */
export function renderReport(element: React.ReactElement): Promise<Buffer> {
  return renderToBuffer(element);
}

/** Formatting shared by the templates. */
export function fmtPct(n: number | null): string {
  return n === null ? "—" : `${n}%`;
}
export function fmtNum(n: number | null): string {
  return n === null ? "—" : String(n);
}
