"use strict";

/**
 * SESS Idle Agent — Electron shell.
 *
 * Thin wiring only: real idle detection (powerMonitor), real HTTP, real tray.
 * All logic lives in tracker.js so it can be tested without a GUI.
 *
 * DELIBERATELY VISIBLE. The tray icon is always shown, the app is not hidden
 * from the task bar or process list, and "Pause tracking" is one click away in
 * the tray menu. An invisible tracking agent is a trust violation this project
 * will not build — that is a product decision consistent with the
 * informed-consent gate on the server, not an oversight.
 */

const { app, Tray, Menu, BrowserWindow, ipcMain, powerMonitor, nativeImage, shell, dialog } =
  require("electron");
const path = require("node:path");
const fs = require("node:fs");

const cfgStore = require("./config");
const { Tracker, DEFAULT_POLL_SECONDS } = require("./tracker");

let tray = null;
let setupWindow = null;
let tracker = null;
let cfg = cfgStore.load();
let pollTimer = null;
let sendTimer = null;

/**
 * ── TRAY ICON ────────────────────────────────────────────────────────
 *
 * Icons are REAL FILES on disk (agent/assets), generated by
 * tools/make-icons.js and committed to the repo.
 *
 * The first version built them from an inline SVG data URL. Electron's
 * nativeImage decodes PNG and JPEG only — NOT SVG — so it silently returned an
 * empty image, and the hard-coded PNG fallback was itself a corrupt base64
 * string (missing IEND, IDAT wouldn't inflate). `new Tray(emptyImage)` gives
 * exactly the symptom that was reported: a tray entry that exists, whose
 * tooltip and menu work, but which draws nothing.
 *
 * Never construct a tray icon from an SVG data URL again.
 */

/**
 * Resolve an asset path that works in BOTH dev (`npm start`, cwd = agent/) and
 * a packaged build (resources inside app.asar, or unpacked beside it).
 *
 * Never uses a bare relative path: those resolve against process.cwd(), which
 * differs between the two, and is the other classic cause of a blank icon.
 */
function assetPath(file) {
  const candidates = [
    // Dev, and packaged-inside-asar (Electron patches fs to read from asar).
    path.join(__dirname, "..", "assets", file),
    // electron-builder with asarUnpack, or extraResources.
    path.join(process.resourcesPath || "", "assets", file),
    path.join(process.resourcesPath || "", "app.asar.unpacked", "assets", file),
  ];
  for (const p of candidates) {
    try {
      if (p && fs.existsSync(p)) return p;
    } catch {
      /* keep trying */
    }
  }
  return null;
}

/**
 * Load the tray icon for a given state.
 *
 * Loudly logs anything that would previously have failed silently — a missing
 * file, or a file that exists but decodes to an empty image.
 */
/** Loaded once per state — refreshTray() runs every 15s and must not re-read
 *  from disk (or re-log) on every tick. */
const iconCache = new Map();

function makeIcon(active) {
  const state = active ? "active" : "paused";
  const cached = iconCache.get(state);
  if (cached) return cached;
  // .ico on Windows (multi-resolution, what the tray actually wants);
  // PNG elsewhere, since macOS/Linux trays don't take .ico.
  const file = process.platform === "win32" ? `tray-${state}.ico` : `tray-${state}-32.png`;

  const resolved = assetPath(file);
  if (!resolved) {
    log(
      `ERROR: tray icon "${file}" not found. Looked beside src/ and in resourcesPath. ` +
        `Run "node tools/make-icons.js" to regenerate it. The tray will be blank.`,
    );
    return nativeImage.createEmpty();
  }

  const img = nativeImage.createFromPath(resolved);
  if (img.isEmpty()) {
    log(
      `ERROR: tray icon "${resolved}" exists but decoded to an EMPTY image — ` +
        `it is corrupt or in a format Electron cannot read (note: SVG is NOT supported). ` +
        `Regenerate with "node tools/make-icons.js". The tray will be blank.`,
    );
    return nativeImage.createEmpty();
  }

  const { width, height } = img.getSize();
  log(`tray icon loaded: ${path.basename(resolved)} (${width}x${height})`);
  iconCache.set(state, img);
  return img;
}

/**
 * What to hand Tray/setImage.
 *
 * On Windows, the PATH STRING — so the shell loads the multi-resolution .ico
 * itself and picks the entry matching the current DPI. Handing it a
 * nativeImage instead makes Chromium decode the .ico to a single 256×256
 * bitmap first, which Windows then downsamples to 16px: same picture, softer
 * edges. Elsewhere, the decoded PNG.
 *
 * makeIcon() still runs first either way — that is what validates the file and
 * logs a clear error instead of failing silently.
 */
function trayIconSource(active) {
  const img = makeIcon(active);
  if (img.isEmpty()) return img; // already logged; let Tray fail loudly

  if (process.platform === "win32") {
    const p = assetPath(`tray-${active ? "active" : "paused"}.ico`);
    if (p) return p;
  }
  return img;
}

/** Electron's cross-platform idle reader — seconds since last input. */
function getIdleSeconds() {
  try {
    return powerMonitor.getSystemIdleTime();
  } catch {
    return 0; // if unavailable, assume active rather than inventing idle time
  }
}

async function post(url, init) {
  const res = await fetch(url, init);
  let json = null;
  try {
    json = await res.json();
  } catch {
    /* non-JSON body is fine */
  }
  return { status: res.status, json };
}

function log(msg) {
  console.log(`[sess-agent] ${new Date().toISOString()} ${msg}`);
}

function persist() {
  cfg.paused = tracker ? tracker.paused : false;
  cfg.buffer = tracker ? tracker.buffer : [];
  cfgStore.save(cfg);
}

function buildMenu() {
  const status = tracker ? tracker.status() : "Not configured";
  const buffered = tracker ? tracker.buffer.length : 0;
  const lastSent =
    tracker && tracker.lastSentAt
      ? new Date(tracker.lastSentAt).toLocaleTimeString()
      : "never";

  return Menu.buildFromTemplate([
    { label: `SESS Idle Agent — ${status}`, enabled: false },
    {
      label: `Last sent: ${lastSent}${buffered ? ` · ${buffered} pending` : ""}`,
      enabled: false,
    },
    ...(tracker && tracker.lastError
      ? [{ label: `Last error: ${tracker.lastError}`.slice(0, 80), enabled: false }]
      : []),
    { type: "separator" },
    {
      label: "What is recorded?",
      click: () =>
        dialog.showMessageBox({
          type: "info",
          title: "What this agent records",
          message: "Idle vs active minutes only.",
          detail:
            "This agent records ONLY whether your machine received keyboard or " +
            "mouse input, summarised as idle/active minutes and sent every 15 minutes.\n\n" +
            "It does NOT capture screenshots, application or window names, websites, " +
            "or what you type. It does not score or rate your work.\n\n" +
            "Tracking runs only while your employer holds your recorded consent, and " +
            "you can pause it at any time from this menu.",
        }),
    },
    { type: "separator" },
    tracker && tracker.paused
      ? {
          label: "Resume tracking",
          click: () => {
            tracker.resume();
            persist();
            refreshTray();
          },
        }
      : {
          label: "Pause tracking",
          click: () => {
            tracker.pause();
            persist();
            refreshTray();
          },
        },
    {
      label: "Change server / token…",
      click: () => openSetup(),
    },
    { type: "separator" },
    {
      label: "Quit",
      click: () => {
        persist();
        app.quit();
      },
    },
  ]);
}

function refreshTray() {
  if (!tray) return;
  const active = tracker && !tracker.paused && !tracker.stoppedByServer;
  tray.setImage(trayIconSource(active));
  tray.setToolTip(`SESS Idle Agent — ${tracker ? tracker.status() : "Not configured"}`);
  tray.setContextMenu(buildMenu());
}

function openSetup() {
  if (setupWindow && !setupWindow.isDestroyed()) {
    setupWindow.focus();
    return;
  }
  setupWindow = new BrowserWindow({
    width: 480,
    height: 460,
    resizable: false,
    title: "SESS Idle Agent — Setup",
    // Same mark on the window/taskbar as in the tray.
    icon: makeIcon(true),
    webPreferences: { preload: path.join(__dirname, "preload.js") },
  });
  setupWindow.setMenuBarVisibility(false);
  setupWindow.loadFile(path.join(__dirname, "setup.html"));
}

function startLoops() {
  if (pollTimer) clearInterval(pollTimer);
  if (sendTimer) clearInterval(sendTimer);

  // Poll idle state.
  pollTimer = setInterval(() => {
    tracker.tick();
    if (tracker.windowElapsed()) {
      const batch = tracker.closeWindow();
      if (tracker.enqueue(batch)) {
        log(`window closed: ${batch.activeMinutes}m active / ${batch.idleMinutes}m idle`);
        persist();
      }
    }
    refreshTray();
  }, DEFAULT_POLL_SECONDS * 1000);

  // Attempt delivery on its own cadence, honouring backoff.
  sendTimer = setInterval(async () => {
    if (!cfgStore.isConfigured(cfg)) return;
    if (tracker.buffer.length === 0 || tracker.stoppedByServer) return;

    const wait = tracker.backoffMs();
    if (wait > 0 && tracker.lastSentAt && Date.now() - tracker.lastSentAt < wait) return;

    const res = await tracker.flush(cfg.serverUrl, cfg.token);
    if (res.sent) log(`sent ${res.sent} batch(es)`);
    if (res.stopped) log(`tracking stopped by server: ${res.error}`);
    persist();
    refreshTray();
  }, 30 * 1000);
}

app.whenReady().then(() => {
  // No dock icon on macOS — this is a tray app, but still fully visible there.
  if (process.platform === "darwin" && app.dock) app.dock.hide();

  tracker = new Tracker({ getIdleSeconds, post, log });
  tracker.buffer = Array.isArray(cfg.buffer) ? cfg.buffer : [];
  if (cfg.paused) tracker.pause();

  // Tray creation can throw on a bad image; without this it would fail during
  // startup and leave the agent running with no visible presence at all —
  // which for a tracking agent is the one outcome that must never happen
  // quietly.
  try {
    tray = new Tray(trayIconSource(!cfg.paused));
    refreshTray();
    tray.on("click", () => tray.popUpContextMenu());
  } catch (e) {
    log(`FATAL: could not create the system tray icon: ${e && e.message ? e.message : e}`);
    dialog.showErrorBox(
      "SESS Idle Agent",
      "The agent could not create its system tray icon and will exit.\n\n" +
        "It will not run without a visible tray presence — an invisible " +
        "tracking agent is not something this software does.\n\n" +
        `Details: ${e && e.message ? e.message : e}`,
    );
    app.quit();
    return;
  }

  if (!cfgStore.isConfigured(cfg)) openSetup();
  startLoops();

  log(`started. config: ${cfgStore.configPath()}`);
});

// Tray app: closing the setup window must not quit the agent.
app.on("window-all-closed", (e) => {
  if (e && typeof e.preventDefault === "function") e.preventDefault();
});

ipcMain.handle("agent:get-config", () => ({
  serverUrl: cfg.serverUrl || "",
  hasToken: Boolean(cfg.token),
  configPath: cfgStore.configPath(),
}));

ipcMain.handle("agent:save-config", (_e, { serverUrl, token }) => {
  const url = String(serverUrl || "").trim();
  const tok = String(token || "").trim();
  if (!/^https?:\/\/\S+$/i.test(url))
    return { ok: false, error: "Enter a valid server URL, e.g. https://sess.example.com" };
  if (!tok) return { ok: false, error: "Enter the agent token issued to you by HR." };

  cfg.serverUrl = url.replace(/\/$/, "");
  cfg.token = tok;
  cfgStore.save(cfg);

  // A new token means a fresh start — clear any server-stop latch.
  tracker.stoppedByServer = false;
  tracker.consecutiveFailures = 0;
  refreshTray();
  return { ok: true };
});

ipcMain.handle("agent:open-config-dir", () => shell.openPath(cfgStore.configDir()));
